---
title: Project Proposal
author: Hayden Atchley
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
    toc: false
    number_sections: false
mainfont: Gentium Book Basic
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

# Introduction

Recently, electric vehicles (EVs) have gained significant public awareness and various levels of support. Generally the adoption of EVs is seen as a good thing, as there are many clear benefits over internal combustion engine (ICE) vehicles. Perhaps the most obvious is that EVs have no emissions, since they are driven entirely by electric motors. Another important advantage is efficiency: while an ICE vehicle will convert around 20% of the fuel's stored energy into motion [@gas-efficiency], EVs are around 90% efficient [@ev-efficiency]. Electric motors are also efficient over a large range of rotational speeds, whereas ICEs are only efficient at a much narrower range of speeds.

However, EVs are not always universally superior to ICE vehicles. One major consideration is that the range of EVs is lower than may be practical in certain applications. Though EVs are more efficient at converting stored energy into motion, gasoline and diesel are more energy-dense than batteries, and so that energy becomes harder to store in an EV by comparison. What truly makes this a concern is the time required to recharge an EV's battery compared to the time to refuel an ICE vehicle's tank. Though there are relatively fast charging standards available, as of now none of them are nearly as fast as filling up a car at a gas station [@epa-charging].

This charging problem, though, is not generally a concern for personal vehicles. Even the slowest of charging standards are able to charge at up to 1.9kW, which if charged either overnight or at a workplace for 8 hours could easily offset a daily commute of 40 miles or more [@epa-charging]. However, for one major part of the transportation industry, namely commercial transportation, EV charging becomes a major consideration. Long-haul trucks, bus rapid transit (BRT), and even local bus networks may not be as well-suited for EV adoption.

# Research Question

So how can a local transit agency decide if electrification of their bus network is a worthwhile pursuit? What are the factors that must be considered, and what are some potential problems and/or solutions? What are the costs of these solutions, and are they practical?

I aim to analyze these questions, with a specific consideration of Utah Transit Authority's (UTA's) bus network, including the Utah Valley eXpress (UVX) BRT as well as the local bus network in the Provo/Orem area. Ultimately I plan to determine what would be required to electrify this bus system and if it is feasible for UTA to do so.

Developing charging infrastructure is the most significant prerequisite to deploying a fleet of EV buses. There are currently several options available for EV charging. Level 1 and 2 charging as well as DC fast charging use a plug-in connector to transfer power [@epa-charging], and other options such as wireless inductive charging exist and are being developed upon [@Klontz1993; @Panchal2018]. I aim to analyze which, if any, of these options would be appropriate.

I also hope to provide somewhat of a framework to help in making similar decisions in the future, both for UTA and other agencies. Recognizing these required considerations and planning for them is an important step in making future electrification easier and more worthwhile.

# Planned Methodology

In order to perform this analysis, I will also need to obtain information on UTA's bus fleets. This will include current vehicle types, fleet sizes, routes, and operating schedules. Currently, the UVX service uses hybrid electric vehicles, but this may not be true for all of the local bus routes. The size and weight of the vehicles is also an important consideration, as that will at least somewhat affect the size of battery pack that can be used, and therefore the range of the vehicle.

I will continue to study the literature surrounding EV charging, and using this information as well as the information about UTA's bus fleets I plan to determine (a) possible path(s) to electrification of the bus service. I will analyze the cost of this(ese) path(s) and suggest a potential "best solution".

# References